<#
  Tear the lab down (Windows/PowerShell version of clean.sh).
  Runs from a normal PowerShell prompt; no WSL or bash needed.

    .\clean.ps1            # containers + volumes + generated state
    .\clean.ps1 -Images    # also remove built images and prune build cache
    .\clean.ps1 -All       # everything above PLUS the pulled base images (Wazuh, TheHive,
                           #   n8n, Caddy) — a bare slate. The next `up` re-pulls several GB.
#>
param([switch]$Images, [switch]$All)
$ErrorActionPreference = 'Continue'
# Work from the lab root. This script lives in lab/scripts/windows/, so climb up
# until the compose file is found.
Set-Location $PSScriptRoot
for ($i = 0; $i -lt 3 -and -not (Test-Path docker-compose.yml); $i++) { Set-Location .. }

Write-Host "== Stopping containers and deleting data volumes ==" -ForegroundColor Cyan
if ($All) {
    # --rmi all removes every image the compose file references: our built ones and the
    # pulled base images both.
    docker compose down -v --rmi all --remove-orphans
} else {
    docker compose down -v --remove-orphans
}

Write-Host "== Removing generated Wazuh certs ==" -ForegroundColor Cyan
Remove-Item -Recurse -Force -ErrorAction SilentlyContinue platform/wazuh/certs/generated

Write-Host "== Removing the runtime ossec.conf (regenerated by start.ps1) ==" -ForegroundColor Cyan
Remove-Item -Force -ErrorAction SilentlyContinue platform/wazuh/ossec.runtime.conf

Write-Host "== Removing the range action log ==" -ForegroundColor Cyan
Remove-Item -Force -ErrorAction SilentlyContinue logs/*.log

if ($Images) {
    Write-Host "== Removing locally-built images ==" -ForegroundColor Cyan
    docker image rm soclab-bank-web soclab-range-control soclab-soc-noise 2>$null
}

if ($Images -or $All) {
    Write-Host "== Pruning build cache ==" -ForegroundColor Cyan
    docker builder prune -f | Out-Null
}

Write-Host "`nClean. Run .\start.ps1 to build a fresh, fully provisioned stack."
