#!/usr/bin/env bash
# Tear the lab down. By default: stop every container, delete all data volumes, and
# remove generated state (certs, runtime config). Bind-mounted content you own
# (.env, threat-intel lists) is left alone.
#
#   ./clean.sh            # containers + volumes + generated state
#   ./clean.sh --images   # also remove the locally-built images and prune build cache
#   ./clean.sh --all      # everything above PLUS the pulled base images (Wazuh, TheHive,
#                         #   n8n, Caddy) — a bare slate. The next `up` re-pulls several GB,
#                         #   which is slow on arm64 under emulation. Use --images for a
#                         #   from-scratch rebuild of just our code without that re-pull.
set -uo pipefail
# Work from the lab root. This script lives in lab/scripts/, so climb
# up until the compose file is found.
cd "$(dirname "$0")"
for _ in 1 2 3; do [ -f docker-compose.yml ] && break; cd ..; done

mode="${1:-}"
case "$mode" in
  ""|--images|--all) ;;
  *) echo "usage: $(basename "$0") [--images|--all]" >&2; exit 2 ;;
esac

echo "== Stopping containers and deleting data volumes =="
if [ "$mode" = "--all" ]; then
  # --rmi all removes every image the compose file references: our built ones and the
  # pulled base images both.
  docker compose down -v --rmi all --remove-orphans
else
  docker compose down -v --remove-orphans
fi

echo "== Removing generated Wazuh certs =="
rm -rf platform/wazuh/certs/generated 2>/dev/null || true

echo "== Removing the runtime ossec.conf (regenerated by start.sh) =="
rm -f platform/wazuh/ossec.runtime.conf 2>/dev/null || true

echo "== Removing the range action log =="
rm -f logs/*.log 2>/dev/null || true

if [ "$mode" = "--images" ]; then
  echo "== Removing locally-built images =="
  docker image rm soclab-bank-web soclab-range-control soclab-soc-noise 2>/dev/null || true
fi

if [ "$mode" = "--images" ] || [ "$mode" = "--all" ]; then
  echo "== Pruning build cache =="
  docker builder prune -f >/dev/null 2>&1 || true
fi

echo
echo "Clean. Run ./start.sh to build a fresh, fully provisioned stack."
